// Curated popular TMDB collection IDs organized by category
// This avoids the slow search-all approach and provides instant loading

export const collectionsByCategory = {
  superhero: [
    { id: 131296, name: 'Marvel Cinematic Universe' },
    { id: 86311, name: 'The Avengers Collection' },
    { id: 529892, name: 'Spider-Man (MCU) Collection' },
    { id: 531241, name: 'Spider-Man (Tobey Maguire) Collection' },
    { id: 573436, name: 'Spider-Man (Andrew Garfield) Collection' },
    { id: 263, name: 'The Dark Knight Collection' },
    { id: 948485, name: 'The Batman Collection' },
    { id: 209131, name: 'Batman Collection' },
    { id: 9485, name: 'The Fast and the Furious Collection' },
    { id: 748, name: 'X-Men Collection' },
    { id: 448150, name: 'Deadpool Collection' },
    { id: 468552, name: 'Wonder Woman Collection' },
    { id: 210814, name: 'Ant-Man Collection' },
    { id: 284433, name: 'Guardians of the Galaxy Collection' },
    { id: 263292, name: 'Captain America Collection' },
    { id: 422834, name: 'Thor Collection' },
    { id: 623911, name: 'Doctor Strange Collection' },
    { id: 618529, name: 'Black Panther Collection' },
    { id: 9735, name: 'Blade Collection' },
    { id: 495, name: 'Superman Collection' },
    { id: 573693, name: 'Aquaman Collection' },
    { id: 724848, name: 'Shazam! Collection' },
    { id: 485, name: 'Hellboy Collection' },
    { id: 912503, name: 'Venom Collection' },
    { id: 726871, name: 'Eternals Collection' },
  ],

  animation: [
    { id: 10194, name: 'Toy Story Collection' },
    { id: 2150, name: 'Shrek Collection' },
    { id: 89137, name: 'Despicable Me Collection' },
    { id: 8354, name: 'Ice Age Collection' },
    { id: 77816, name: 'Kung Fu Panda Collection' },
    { id: 14740, name: 'Madagascar Collection' },
    { id: 386382, name: 'Frozen Collection' },
    { id: 468222, name: 'The Incredibles Collection' },
    { id: 137697, name: 'Finding Nemo Collection' },
    { id: 87118, name: 'Cars Collection' },
    { id: 264, name: 'The Lion King Collection' },
    { id: 722961, name: 'Minions Collection' },
    { id: 427084, name: 'Hotel Transylvania Collection' },
    { id: 386534, name: 'Trolls Collection' },
    { id: 39940, name: 'How to Train Your Dragon Collection' },
    { id: 153010, name: 'Monsters, Inc. Collection' },
    { id: 721452, name: 'Encanto Collection' },
    { id: 521281, name: 'Wreck-It Ralph Collection' },
    { id: 97459, name: 'Cloudy with a Chance of Meatballs Collection' },
    { id: 97461, name: 'Smurfs Collection' },
    { id: 280588, name: 'The Secret Life of Pets Collection' },
    { id: 594164, name: 'Sing Collection' },
    { id: 404825, name: 'The Boss Baby Collection' },
    { id: 531330, name: 'The Croods Collection' },
    { id: 173710, name: 'Puss in Boots Collection' },
  ],

  action: [
    { id: 645, name: 'James Bond Collection' },
    { id: 9485, name: 'The Fast and the Furious Collection' },
    { id: 87359, name: 'Mission: Impossible Collection' },
    { id: 404609, name: 'John Wick Collection' },
    { id: 2344, name: 'The Matrix Collection' },
    { id: 528, name: 'The Terminator Collection' },
    { id: 8650, name: 'Transformers Collection' },
    { id: 1570, name: 'Die Hard Collection' },
    { id: 31562, name: 'The Expendables Collection' },
    { id: 8945, name: 'Mad Max Collection' },
    { id: 2883, name: 'Indiana Jones Collection' },
    { id: 495, name: 'Jack Reacher Collection' },
    { id: 1241, name: 'Harry Potter Collection' },
    { id: 735, name: 'Rocky Collection' },
    { id: 448150, name: 'Deadpool Collection' },
    { id: 2806, name: 'Rush Hour Collection' },
    { id: 573436, name: 'Top Gun Collection' },
    { id: 14890, name: 'Rambo Collection' },
    { id: 126209, name: 'The Purge Collection' },
    { id: 33514, name: 'The Hunger Games Collection' },
  ],

  fantasy: [
    { id: 1241, name: 'Harry Potter Collection' },
    { id: 119, name: 'The Lord of the Rings Collection' },
    { id: 121938, name: 'The Hobbit Collection' },
    { id: 1565, name: 'Pirates of the Caribbean Collection' },
    { id: 420, name: 'The Chronicles of Narnia Collection' },
    { id: 435259, name: 'Wizarding World Collection' },
    { id: 295, name: 'Pirates of the Caribbean Collection' },
    { id: 726871, name: 'Eternals Collection' },
    { id: 348, name: 'Alien Collection' },
    { id: 735712, name: 'Dune Collection' },
  ],

  horror: [
    { id: 91697, name: 'Halloween Collection' },
    { id: 2980, name: 'Friday the 13th Collection' },
    { id: 525, name: 'A Nightmare on Elm Street Collection' },
    { id: 656, name: 'Saw Collection' },
    { id: 313086, name: 'The Conjuring Collection' },
    { id: 86066, name: 'Insidious Collection' },
    { id: 8864, name: 'Final Destination Collection' },
    { id: 31412, name: 'Paranormal Activity Collection' },
    { id: 126209, name: 'The Purge Collection' },
    { id: 402074, name: 'Annabelle Collection' },
    { id: 348, name: 'Alien Collection' },
    { id: 2602, name: 'Child\'s Play Collection' },
    { id: 2602, name: 'Scream Collection' },
    { id: 9743, name: 'The Texas Chainsaw Massacre Collection' },
    { id: 8091, name: 'Resident Evil Collection' },
    { id: 17255, name: 'Underworld Collection' },
    { id: 8581, name: 'A Quiet Place Collection' },
    { id: 726, name: 'Predator Collection' },
    { id: 295, name: 'The Exorcist Collection' },
    { id: 756, name: 'Hannibal Lecter Collection' },
  ],

  scifi: [
    { id: 10, name: 'Star Wars Collection' },
    { id: 151, name: 'Star Trek Collection' },
    { id: 2344, name: 'The Matrix Collection' },
    { id: 328, name: 'Jurassic Park Collection' },
    { id: 422837, name: 'Jurassic World Collection' },
    { id: 735712, name: 'Dune Collection' },
    { id: 348, name: 'Alien Collection' },
    { id: 87096, name: 'Avatar Collection' },
    { id: 264, name: 'Back to the Future Collection' },
    { id: 173710, name: 'Planet of the Apes Reboot Collection' },
    { id: 8650, name: 'Transformers Collection' },
    { id: 528, name: 'The Terminator Collection' },
    { id: 535313, name: 'Godzilla Collection' },
    { id: 135495, name: 'Maze Runner Collection' },
    { id: 726, name: 'Predator Collection' },
    { id: 115570, name: 'Pacific Rim Collection' },
    { id: 427084, name: 'Cloverfield Collection' },
    { id: 33514, name: 'The Hunger Games Collection' },
    { id: 131635, name: 'The Divergent Series Collection' },
    { id: 131296, name: 'Men in Black Collection' },
  ],

  thriller: [
    { id: 404609, name: 'John Wick Collection' },
    { id: 87359, name: 'Mission: Impossible Collection' },
    { id: 2883, name: 'Indiana Jones Collection' },
    { id: 645, name: 'James Bond Collection' },
    { id: 2344, name: 'The Matrix Collection' },
    { id: 126209, name: 'The Purge Collection' },
    { id: 756, name: 'Hannibal Lecter Collection' },
    { id: 304378, name: 'Now You See Me Collection' },
    { id: 34055, name: 'Taken Collection' },
    { id: 295130, name: 'Knives Out Collection' },
    { id: 86347, name: 'The Equalizer Collection' },
    { id: 9485, name: 'The Fast and the Furious Collection' },
  ],

  comedy: [
    { id: 86119, name: 'The Hangover Collection' },
    { id: 2806, name: 'Rush Hour Collection' },
    { id: 33, name: 'Ghostbusters Collection' },
    { id: 115776, name: 'Ted Collection' },
    { id: 528, name: '21 Jump Street Collection' },
    { id: 216, name: 'Home Alone Collection' },
    { id: 91698, name: 'Bad Boys Collection' },
    { id: 2150, name: 'Shrek Collection' },
    { id: 115762, name: 'Pitch Perfect Collection' },
    { id: 86066, name: 'Dumb and Dumber Collection' },
    { id: 115, name: 'Austin Powers Collection' },
    { id: 85943, name: 'Grown Ups Collection' },
    { id: 96871, name: 'Neighbors Collection' },
    { id: 352789, name: 'Daddy\'s Home Collection' },
    { id: 373155, name: 'Bad Moms Collection' },
  ],

  drama: [
    { id: 230, name: 'The Godfather Collection' },
    { id: 735, name: 'Rocky Collection' },
    { id: 939470, name: 'Creed Collection' },
    { id: 263, name: 'The Dark Knight Collection' },
    { id: 119, name: 'The Lord of the Rings Collection' },
    { id: 645, name: 'James Bond Collection' },
  ],

  crime: [
    { id: 230, name: 'The Godfather Collection' },
    { id: 1570, name: 'Die Hard Collection' },
    { id: 404609, name: 'John Wick Collection' },
    { id: 86347, name: 'The Equalizer Collection' },
    { id: 9485, name: 'The Fast and the Furious Collection' },
    { id: 645, name: 'James Bond Collection' },
    { id: 34055, name: 'Taken Collection' },
    { id: 91698, name: 'Bad Boys Collection' },
    { id: 295130, name: 'Knives Out Collection' },
  ],

  family: [
    { id: 216, name: 'Home Alone Collection' },
    { id: 328, name: 'Jurassic Park Collection' },
    { id: 10194, name: 'Toy Story Collection' },
    { id: 2150, name: 'Shrek Collection' },
    { id: 386382, name: 'Frozen Collection' },
    { id: 264, name: 'The Lion King Collection' },
    { id: 89137, name: 'Despicable Me Collection' },
    { id: 39940, name: 'How to Train Your Dragon Collection' },
    { id: 87118, name: 'Cars Collection' },
    { id: 1565, name: 'Pirates of the Caribbean Collection' },
    { id: 468222, name: 'The Incredibles Collection' },
    { id: 386534, name: 'Trolls Collection' },
    { id: 420, name: 'The Chronicles of Narnia Collection' },
    { id: 722961, name: 'Minions Collection' },
    { id: 427084, name: 'Hotel Transylvania Collection' },
  ],

  adventure: [
    { id: 2883, name: 'Indiana Jones Collection' },
    { id: 1565, name: 'Pirates of the Caribbean Collection' },
    { id: 328, name: 'Jurassic Park Collection' },
    { id: 119, name: 'The Lord of the Rings Collection' },
    { id: 121938, name: 'The Hobbit Collection' },
    { id: 33514, name: 'The Hunger Games Collection' },
    { id: 735712, name: 'Dune Collection' },
    { id: 87096, name: 'Avatar Collection' },
    { id: 10, name: 'Star Wars Collection' },
    { id: 420, name: 'The Chronicles of Narnia Collection' },
  ],

  war: [
    { id: 735, name: 'Rocky Collection' },
    { id: 14890, name: 'Rambo Collection' },
    { id: 31562, name: 'The Expendables Collection' },
    { id: 528, name: 'The Terminator Collection' },
  ],

  spy: [
    { id: 645, name: 'James Bond Collection' },
    { id: 87359, name: 'Mission: Impossible Collection' },
    { id: 391860, name: 'Kingsman Collection' },
    { id: 115, name: 'Austin Powers Collection' },
    { id: 304378, name: 'Now You See Me Collection' },
  ],

  sports: [
    { id: 735, name: 'Rocky Collection' },
    { id: 939470, name: 'Creed Collection' },
  ],

  romance: [
    { id: 386382, name: 'Frozen Collection' },
    { id: 115762, name: 'Pitch Perfect Collection' },
    { id: 373155, name: 'Bad Moms Collection' },
  ],

  musical: [
    { id: 115762, name: 'Pitch Perfect Collection' },
  ],

  disaster: [
    { id: 535313, name: 'Godzilla Collection' },
    { id: 8945, name: 'Mad Max Collection' },
  ],

  western: [
    { id: 8945, name: 'Mad Max Collection' },
  ],

  martial_arts: [
    { id: 2806, name: 'Rush Hour Collection' },
    { id: 77816, name: 'Kung Fu Panda Collection' },
  ],
};

// Flat unique list of all collection IDs for batch fetching
export const allCollectionIds = [...new Set(
  Object.values(collectionsByCategory).flatMap(arr => arr.map(c => c.id))
)];

// Category metadata for display
export const collectionCategories = [
  { id: 'all', name: 'All', icon: '🎬' },
  { id: 'superhero', name: 'Superhero', icon: '🦸' },
  { id: 'action', name: 'Action', icon: '💥' },
  { id: 'animation', name: 'Animation', icon: '🎨' },
  { id: 'scifi', name: 'Sci-Fi', icon: '🚀' },
  { id: 'horror', name: 'Horror', icon: '👻' },
  { id: 'fantasy', name: 'Fantasy', icon: '🧙' },
  { id: 'thriller', name: 'Thriller', icon: '🔍' },
  { id: 'comedy', name: 'Comedy', icon: '😂' },
  { id: 'drama', name: 'Drama', icon: '🎭' },
  { id: 'crime', name: 'Crime', icon: '🔫' },
  { id: 'family', name: 'Family', icon: '👨‍👩‍👧‍👦' },
  { id: 'adventure', name: 'Adventure', icon: '🗺️' },
  { id: 'spy', name: 'Spy', icon: '🕵️' },
  { id: 'sports', name: 'Sports', icon: '🏆' },
  { id: 'war', name: 'War', icon: '⚔️' },
  { id: 'romance', name: 'Romance', icon: '💕' },
  { id: 'disaster', name: 'Disaster', icon: '🌋' },
  { id: 'western', name: 'Western', icon: '🤠' },
  { id: 'martial_arts', name: 'Martial Arts', icon: '🥋' },
  { id: 'musical', name: 'Musical', icon: '🎵' },
];
